/**
 * Block-Based Abbreviation Expansion System
 *
 * Core Concept:
 * - Each interchange line is split into ordered blocks (tokens)
 * - Each block is evaluated independently against known abbreviations
 * - Variants are generated by combining block expansions (not keyword stuffing)
 * - Unknown blocks are preserved and passed through
 */

// ── Block Abbreviation Library ──────────────────────────────────────────────

/**
 * Known abbreviation equivalents for each block type.
 * Each block expands to a list of valid variants.
 */
const BLOCK_ABBREVIATIONS: Record<string, string[]> = {
  // Card Networks
  "VI": ["VI", "VISA"],
  "MC": ["MC", "MASTERCARD"],
  "DS": ["DS", "DISCOVER"],
  "AX": ["AX", "AMEX", "AMERICAN EXPRESS"],

  // Geographic/Region
  "US": ["US", "USA", "UNITED STATES"],
  "INTL": ["INTL", "INT", "INTERNATIONAL"],

  // Card Types
  "BUS": ["BUS", "BUSINESS"],
  "CORP": ["CORP", "CORPORATE"],
  "PUR": ["PUR", "PURCH", "PURCHASING"],
  "COMM": ["COMM", "COMMERCIAL", "COMML"],
  "FLEET": ["FLEET", "FLT"],

  // Tier/Level Indicators
  "TR1": ["TR1", "T1", "TIER1", "TIER 1"],
  "TR2": ["TR2", "T2", "TIER2", "TIER 2"],
  "TR3": ["TR3", "T3", "TIER3", "TIER 3"],
  "TR4": ["TR4", "T4", "TIER4", "TIER 4"],
  "TR5": ["TR5", "T5", "TIER5", "TIER 5"],
  "T1": ["T1", "TR1", "TIER1", "TIER 1"],
  "T2": ["T2", "TR2", "TIER2", "TIER 2"],
  "T3": ["T3", "TR3", "TIER3", "TIER 3"],
  "T4": ["T4", "TR4", "TIER4", "TIER 4"],
  "T5": ["T5", "TR5", "TIER5", "TIER 5"],

  // Product Indicators
  "PRD": ["PRD", "PROD", "PRODUCT"],
  "PRD 1": ["PRD 1", "PROD 1", "PRODUCT 1"],
  "PRD 2": ["PRD 2", "PROD 2", "PRODUCT 2"],
  "PRD 3": ["PRD 3", "PROD 3", "PRODUCT 3"],
  "PRODUCT 1": ["PRODUCT 1", "PROD 1", "PRD 1"],
  "PRODUCT 2": ["PRODUCT 2", "PROD 2", "PRD 2"],
  "PRODUCT 3": ["PRODUCT 3", "PROD 3", "PRD 3"],

  // Level Indicators
  "LEVEL 1": ["LEVEL 1", "LVL 1", "LVL1", "L1"],
  "LEVEL 2": ["LEVEL 2", "LVL 2", "LVL2", "L2"],
  "LEVEL 3": ["LEVEL 3", "LVL 3", "LVL3", "L3"],
  "LEVEL 4": ["LEVEL 4", "LVL 4", "LVL4", "L4"],
  "LEVEL 5": ["LEVEL 5", "LVL 5", "LVL5", "L5"],
  "LVL": ["LVL", "LEVEL"],

  // Data Rate Indicators
  "DATA RATE 1": ["DATA RATE 1", "DATA RATE I", "DATA RT 1", "DATA RT I"],
  "DATA RATE 2": ["DATA RATE 2", "DATA RATE II", "DATA RT 2", "DATA RT II"],
  "DATA RATE 3": ["DATA RATE 3", "DATA RATE III", "DATA RT 3", "DATA RT III"],
  "DATA RT": ["DATA RT", "DATA RATE"],
  "RT": ["RT", "RATE"],

  // Standard/Quality Indicators
  "STD": ["STD", "STANDARD"],
  "STANDARD": ["STANDARD", "STD"],

  // Card Present/Not Present
  "CNP": ["CNP", "CARD NOT PRESENT"],
  "CP": ["CP", "CARD PRESENT"],

  // Qualification Status
  "NON QUAL": ["NON QUAL", "NON-QUAL", "NONQUAL", "NON QUALIFIED"],
  "QUAL": ["QUAL", "QUALIFIED"],

  // EIRF (Electronic Interchange Reimbursement Fee)
  "EIRF": ["EIRF", "E-IRF"],

  // CPS (Custom Payment Service)
  "CPS": ["CPS"],

  // Special Card Types
  "WORLD": ["WORLD", "WLD"],
  "ELITE": ["ELITE", "ELIT"],
  "WORLD ELITE": ["WORLD ELITE", "WORLD-ELITE", "WLD ELITE"],

  // Other common abbreviations
  "REG": ["REG", "REGULATED"],
  "CR": ["CR", "CREDIT"],
  "DB": ["DB", "DEBIT"],
  "LRG": ["LRG", "LARGE"],
  "MKT": ["MKT", "MARKET"],
  "NFUEL": ["NFUEL", "NON-FUEL", "NON FUEL"],
};

// ── Block Tokenization ──────────────────────────────────────────────────────

/**
 * Tokenize a line into ordered blocks.
 * Handles multi-word blocks (e.g., "PRD 1", "DATA RATE 2").
 */
export function tokenizeLine(line: string): string[] {
  const normalized = line.toUpperCase().trim();

  // Split on common delimiters but preserve meaningful spaces
  const parts = normalized.split(/[\s\-_/]+/).filter(Boolean);

  const blocks: string[] = [];
  let i = 0;

  while (i < parts.length) {
    // Try to match multi-word blocks first (longest match wins)
    let matched = false;

    // Try combinations of 2-3 consecutive parts
    for (let len = 3; len >= 2; len--) {
      if (i + len <= parts.length) {
        const candidate = parts.slice(i, i + len).join(" ");
        if (BLOCK_ABBREVIATIONS[candidate]) {
          blocks.push(candidate);
          i += len;
          matched = true;
          break;
        }
      }
    }

    // If no multi-word match, take single part
    if (!matched) {
      blocks.push(parts[i]);
      i++;
    }
  }

  return blocks;
}

// ── Block Expansion ──────────────────────────────────────────────────────────

/**
 * Expand a single block to all its known variants.
 * Unknown blocks are preserved (passed through).
 */
export function expandBlock(block: string): string[] {
  const upper = block.toUpperCase();
  return BLOCK_ABBREVIATIONS[upper] || [block]; // Pass through if unknown
}

// ── Line Variant Generation ──────────────────────────────────────────────────

/**
 * Generate all valid line variants by combining block expansions.
 * Uses combinatorial approach but maintains structure.
 */
export function generateLineVariants(line: string): string[] {
  const blocks = tokenizeLine(line);
  const expandedBlocks = blocks.map(expandBlock);

  // Generate all combinations using cartesian product
  function cartesianProduct(arrays: string[][]): string[][] {
    if (arrays.length === 0) return [[]];
    if (arrays.length === 1) return arrays[0].map(x => [x]);

    const [first, ...rest] = arrays;
    const restProduct = cartesianProduct(rest);

    return first.flatMap(x =>
      restProduct.map(combo => [x, ...combo])
    );
  }

  const combinations = cartesianProduct(expandedBlocks);

  // Join blocks back into lines (preserve space separation)
  return combinations.map(combo => combo.join(" "));
}

// ── Integration Helper ───────────────────────────────────────────────────────

/**
 * Expand a line into all variants for matching.
 * This replaces the old expandProcessorAliases approach.
 */
export function expandLineForMatching(rawLine: string): string {
  const variants = generateLineVariants(rawLine);

  // Join all variants with space separator for keyword matching
  // The matcher will check if keywords exist in ANY variant
  return variants.join(" ");
}

// ── Diagnostic/Debug Helpers ─────────────────────────────────────────────────

/**
 * Show how a line is tokenized and expanded (for debugging)
 */
export function explainExpansion(line: string): {
  original: string;
  blocks: string[];
  expandedBlocks: string[][];
  variants: string[];
  variantCount: number;
} {
  const blocks = tokenizeLine(line);
  const expandedBlocks = blocks.map(expandBlock);
  const variants = generateLineVariants(line);

  return {
    original: line,
    blocks,
    expandedBlocks,
    variants,
    variantCount: variants.length,
  };
}
